export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const CHANGE_LANGUAGE= 'CHANGE_LANGUAGE';
export const FETCH_SERVICE = 'GET/FETCH_SERVICE';
export const FETCH_SLIDER_BANNER= 'GET/FETCH_SLIDER_BANNER';
export const FETCH_SERVICE_SLIDER= 'GET/FETCH_SERVICE_SLIDER';
